import './load-env';
import { getAllChapters } from '../lib/chapters';
import { writeFile } from 'fs/promises';
import { join } from 'path';
import clientPromise from '../lib/mongodb';

async function exportChapters() {
  try {
    console.log('Fetching chapters...');
    const chapters = await getAllChapters();
    console.log(`Found ${chapters.length} chapters.`);

    const fileContent = `// Auto-generated by scripts/export_chapters.ts
import { Chapter } from './chapters';

export const STATIC_CHAPTERS: Chapter[] = ${JSON.stringify(chapters, null, 2)};
`;

    const outputPath = join(process.cwd(), 'lib', 'static-chapters.ts');
    await writeFile(outputPath, fileContent, 'utf-8');
    console.log(`Chapters exported to ${outputPath}`);
  } catch (error) {
    console.error('Error exporting chapters:', error);
    process.exit(1);
  } finally {
     // Check if we can close the connection cleanly
     try {
       const client = await clientPromise;
       await client.close();
     } catch (e) {
       // Ignore close errors if client wasn't initialized
     }
  }
}

exportChapters();
